### ISSUE TITLE
 Child combinator `>` inside `:not()` is not a valid selector

### ISSUE THREAD

**Issue by Nivani** [dperini/nwsapi#107]
The following selector throws an error using `nwsapi`, but not in a web browser:
```css
button:not(.k-dropdownlist > .k-button):not(.k-colorpicker > .k-button)
```

This selector is used by Kendo UI, a commercial component library.

I was able to narrow it down to the use of the child combinator `>` inside `:not()`.

Node.js script that reproduces the issue:

```js
const jsdom = require("jsdom");

const dom = new jsdom.JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
const selectors = [
  "button:not(.k-dropdownlist > .k-button):not(.k-colorpicker > .k-button)",
  "button:not(.k-dropdownlist > .k-button)",
  "button:not(.k-dropdownlist)",
  ".k-dropdownlist > button.k-button",
];

selectors.forEach((selector) => {
  try {
    dom.window.document.querySelectorAll(selector);
    console.log(`✅ Selector "${selector}" is ok`);
  } catch (e) {
    console.log(`❌ Selector "${selector}" throws an error:`, e.message);
  }
});

```

Output:
```
❌ Selector "button:not(.k-dropdownlist > .k-button):not(.k-colorpicker > .k-button)" throws an error: 'button:not(.k-dropdownlist > .k-button):not(.k-colorpicker > .k-button)' is not a valid selector
❌ Selector "button:not(.k-dropdownlist > .k-button)" throws an error: 'button:not(.k-dropdownlist > .k-button)' is not a valid selector
✅ Selector "button:not(.k-dropdownlist)" is ok
✅ Selector ".k-dropdownlist > button.k-button" is ok
```

Tested with Node v20.9.0

I've seen other issues where selectors broke when upgrading from 2.2.2 to 2.2.3, but these don't work in 2.2.2 either.

**Comment by dperini** [comment]
@Nivani
could you please check if the current "nwsapi" master branch here on github fixes the problem ?
I haven't released a new package on NPM yet but if the problem is fixed I can plan a new release.

**Comment by Nivani** [comment]
@dperini thanks! It works when I use the master branch.

I've tested both the example above and the project that's using Kendo UI.

**Comment by dperini** [comment]
@Nivani 
thank you for the prompt answer.
Will wait a few more confirmations to ensure I didn't create any regression or problem.
Then I will release 2.2.10 on NPM and have others happy too.
Forgive the delay in fixing this, appreciate your help and contribution.
