### ISSUE TITLE
Whitespace around operator breaks nth-child selectors

### ISSUE THREAD

**Issue by JKillian** [dperini/nwsapi#20]
Given this html page:

```html
<!DOCTYPE html>
<script type="text/javascript" src="src/nwsapi.js"></script>
<div>
  <p>first</p>
  <p>second</p>
  <p>third</p>
</div>
```

The selector `p:nth-child(2n + 1)` only works if `SIMPLENOT` is false:

![image](https://user-images.githubusercontent.com/1400151/44289596-01b5cb80-a243-11e8-858c-e88bf9121e1e.png)

The same selector without whitespace, `p:nth-child(2n+1)`, works in both modes. [The spec](https://drafts.csswg.org/selectors-3/#nth-child-pseudo) allows whitespace, so ideally both selectors should always work.

In addition, prettier seems to autoformat CSS selectors with spaces in this situation. So this bug leads to a sad case where autoformatting your code with prettier can cause unit tests to break in the Jest -> JSDOM -> NWSAPI stack (or anything else relying on JSDOM to run tests).

Thanks for the help!

**Edit:** I believe the issue goes beyond `SIMPLE_NOT`, for example, `p:nth-child(2n - 1)` doesn't work in either mode.

**Comment by dperini** [comment]
That seems easy to fix, I will have a look asap.

Probably these are the consequence of applying the following commit (security fix):
https://github.com/dperini/nwsapi/commit/acaa23bb6fc820e638d27cd8948b6f18ed187e3b

Are you using latest version (2.0.8) ?

**Comment by JKillian** [comment]
Thanks for the fix in https://github.com/dperini/nwsapi/commit/9dfcc2ab4c383d860c67cfb19effe584f8a8c553 @dperini! I'm going to close this issue out as it's resolved now.
