### ISSUE TITLE
jsdom should be in devDependencies

### ISSUE THREAD

**Issue by renchap** [dperini/nwsapi#25]
In the latest release you added `jsdom` as a dependency, but as it is only used for tests it should a dev dependency to avoid any package user installing it.

**Comment by nickschot** [comment]
This dependency also broke node 6 support as that version of jsdom does not support it.

**Comment by dperini** [comment]
@renchap @nickschot thank you for reporting the issue.
I simply removed the dependencies from the package.json file
then published a new version 2.1.3. No functional changes committed.

**Comment by renchap** [comment]
Thanks!
