### ISSUE TITLE
nwsapi implements webkit‑prefixed pseudo behaviour for pseudo‑classes instead of pseudo‑elements

### ISSUE THREAD

**Issue by ExE-Boss** [dperini/nwsapi#26]
Case in&nbsp;point: https://github.com/dperini/nwsapi/blob/4077276bc5ed1e2b56f12bf409b328e918d67784/src/nwsapi.js#L86-L87

https://drafts.csswg.org/selectors-4/#compat

**Comment by dperini** [comment]
@ExE-Boss thank you for reporting the issue.
I will merge your pull request.
Help appreciated !
