### ISSUE TITLE
DocumentFragments do not implement getElementById, but nwsapi assumes they do

### ISSUE THREAD

**Issue by domenic** [dperini/nwsapi#3]
```
     TypeError: fragment.getElementById is not a function
      at hasDuplicateId (node_modules\nwsapi\src\nwsapi.js:271:34)
      at byId (node_modules\nwsapi\src\nwsapi.js:301:33)
      at node_modules\nwsapi\src\nwsapi.js:252:61
      at Object.Resolver [as factory] (eval at compile (node_modules\nwsapi\src\nwsapi.js:687:17), <anonymous>:3:71)
      at Object._querySelectorAll [as select] (node_modules\nwsapi\src\nwsapi.js:1287:23)
      at DocumentFragmentImpl.<anonymous> (lib\jsdom\living\nodes\ParentNode-impl.js:68:24)
```

Here the last line in the stack trace is essentially

```js
  const list = matcher.select(selectors, someDocumentFragment);
```

**Comment by dperini** [comment]
@domenic,

getElementsByTagName and getElementsByClassName are not implemented for fragments, but getElementById is implemented in every browser I tested.
Try the following snippet in the console:

    var frag, elem;
    
    frag = document.createDocumentFragment();
    elem = document.createElement('div');
    frag.appendChild(elem);
    elem.id = 'foo';
    
    console.log(frag.getElementById);
    console.log(frag.getElementById('foo'));

the output will be:

    function getElementById()
    <div id="foo">

maybe this needs to be implemented in 'jsdom' too.

**Comment by Zirro** [comment]
Ah, indeed: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/NonElementParentNode.webidl

**Comment by domenic** [comment]
Thanks; will try to get this fixed in jsdom.

**Comment by dperini** [comment]
@domenic @Zirro,
feel free to suggest API or methods name changes and/or correct my typos wherever you find them, my english comments surely needs corrections.
Also notice that the signature for the 'match' method has changed from 'nwmatcher' to have a uniform set of API so the argument list order is now "(selector, context, callback)".

**Comment by dperini** [comment]
@domenic @Zirro 
I have published "nwsapi" with the beta status on "npmjs".
Maybe we can implement it in "jsdom" replacing "nwmatcher".
I have done extensive testing. It seems functional as much as the current version of "nwmatcher".
There are new CSS4 pseudo-class capabilities and much improved performances and compliance.
