### ISSUE TITLE
Throw when repeated complex select

### ISSUE THREAD

**Issue by pmdartus** [dperini/nwsapi#32]
### Basic info:

- **nwapi version:** `2.2.0`

### Minimal reproduction case

Live example: [jsbin](https://jsbin.com/henoduyamo/1/edit?html,js,output)

```js
NW.Dom.install();
NW.Dom.select('.foo, .foo, .bar', document.body);  // pass
NW.Dom.select('.foo, .foo, .bar', document.body); // error

// nwsapi.js:1450 Uncaught TypeError: Cannot read property '0' of undefined
//    at Object._querySelectorAll [as select]
```

### Observations

This is a real conner case, this issue only happens when there is a duplicate class selector and different class selector in a compound selector and when the selector runs multiple times. Context in the original [issue](https://github.com/jsdom/jsdom/issues/2680).

**Comment by dperini** [comment]
@pmdartus thank you for reporting this issue.
A quick look to line 1450 reveal there is an issue in the way I perform the needed check.
So I confirm the problem you reported exists and will be fixed it as soon as work load allows.
Appreciate your time to test and report the issue.

**Comment by dperini** [comment]
@pmdartus 
issue should be fixed, thank you for you help reporting.
