### ISSUE TITLE
New release 2.2.1

### ISSUE THREAD

**Issue by mishaaq** [dperini/nwsapi#42]
Hey @dperini, would you like to release new version with recent fixes? v2.2.0 is pretty outdated.

**Comment by dperini** [comment]
@mishaaq yes I will be working on that soon.
Thank you for the push :+1:

**Comment by mishaaq** [comment]
@dperini I'm not pushing - it was just a friendly reminder ;).

**Comment by dperini** [comment]
@mishaaq 
the long awaited new release is on sight.
ETA before the end of June (hopefully).

**Comment by EladHeller** [comment]
Hey @dperini, there is an update?
Can I help with that?

**Comment by dperini** [comment]
@EladHeller yes help will be much appreciated.
I am starting to release patches already known to fix existing problem.
The help I wish is to avoid creating new problems, so testing is essential.

**Comment by dperini** [comment]
@EladHeller 
thank you for offering help.
More testing is necessary & welcome.
