### ISSUE TITLE
Stop matching <link> for :link, :visited, and :any-link

### ISSUE THREAD

**Issue by domenic** [dperini/nwsapi#43]
The spec changed in this regard in https://github.com/whatwg/html/commit/1e0ee7fc1aa490212a8655ceccaf12accb5b9be9 . There is a test in https://github.com/web-platform-tests/wpt/blob/master/html/semantics/selectors/pseudo-classes/link.html

**Comment by dperini** [comment]
@domenic 
the reported problem should be resolved in: https://github.com/dperini/nwsapi/commit/373ea44fdf6d02c70ea81fa370bdcce44060820c
