### ISSUE TITLE
In unit tests: RangeError: Invalid string length 

### ISSUE THREAD

**Issue by silvanaweb** [dperini/nwsapi#50]
While using react testing library that uses this library, I have encountered a difficult-to-find error when running unit tests that were just breaking and showing the following message: 

```
node_modules/nwsapi/src/nwsapi.js:893
      source = ‘n=e;while((e=e.parentElement)){’ + source + ‘}e=n;’;
```

After hours of investigation, I have found out that one of the React styled components I was using had a tiny mistake in its styles.
Something like:
```
  tbody th {
    vertical-align: middle;

    > span {
      display: inline-block;
      padding: 0;
    }
  }ç
```

Where a character was out of the parenthesis.

**Comment by omeralper** [comment]
I spent a day to find this out also.

**Comment by Twonky-Chris** [comment]
I had the same problem.

**Comment by richard-ling** [comment]
I just got the same thing today, too.
My jest test bombs out with the same error on the same line.
In my case, `compileSelector` is called with `expression` = '.makeStyles-root _:-ms-fullscreen'.
The parser gets stuck in an endless cycle with `selector` = ` _:-ms-fullscreen` (note the leading space):
   - at the top of the `while` loop, `symbol` is a space, so matches the 'Descendant combinator' case
   - `match` is set to `[' _:-ms-fullscreen', '_:-ms-fullscreen']`, `source` is set to a string that embeds itself
   - at the bottom of the `while` loop, `selector` is set to `match.pop()` i.e. '_:-ms-fullscreen' (no leading space).
   - on next iteration of the `while` loop, `symbol` is set to `_`
   - this does not match any case, so emits 'invalid selector' message
   - at the bottom of the `while` loop, `selector` is set to `match.pop()` i.e. ' _:-ms-fullscreen' (with leading space)
   - this is the value of `selector` at the start of the cycle, so the cycle repeats.
On each cycle the `source` string grows, eventually exhausting memory.

NOTE: the recommendation for using ` _:-ms-fullscreen` comes from here:
https://stackoverflow.com/questions/45973976/apply-only-to-ie-11-within-media-query-for-screen-size
I'm not sure if it is valid CSS, as `_` is not a tagname, but in any case nwsapi should not crash.

Seems that this error will occur whenever there is a space followed by an invalid selector.

**Comment by richard-ling** [comment]
Turns out issue #46 is the exact problem I described above
