### ISSUE TITLE
[v2.2.0] DoS vulnerability in npm package

### ISSUE THREAD

**Issue by dominicnguyenwt** [dperini/nwsapi#56]
@dperini 

Hi,

do you have any plans for updating the npm package? I noticed a vulnerability issue in the 2.2.0 package version:
https://security.snyk.io/vuln/SNYK-JS-NWSAPI-2841516

It seems that the master branch in this repo contains a fix for it.

Thanks!

**Comment by dperini** [comment]
Published release 2.2.1
