### ISSUE TITLE
element selectors became case-sensitive in 2.2.1, in violation of spec

### ISSUE THREAD

**Issue by bakkot** [dperini/nwsapi#57]
A simple repro:

```html
<!doctype html>
<body>
<p></p>
<script src="src/nwsapi.js"></script>
<script>
NW.Dom.install();
document.body.innerHTML += [document.body.querySelector('P') != null, document.body.querySelector('p') != null].join(', ');
</script>
```

With 2.2.1 this prints `false, true`, when it should be `true, true`.

Per [spec](https://www.w3.org/TR/selectors-4/#case-sensitive), "All Selectors syntax is [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive)".

I suspect this is due to https://github.com/dperini/nwsapi/pull/37 or one of the followup commits, though I haven't investigated.

(Discovered because this broke jsdom, which broke ecmarkup, which broke [one of the JavaScript specifications](https://matrixlogs.bakkot.com/TC39_Delegates/2022-06-29#L0).)

**Comment by dperini** [comment]
@bakkot 
working on a quick fix, probably reverting #37

**Comment by dperini** [comment]
Should be fixed. Please check / test and let me know.

**Comment by bakkot** [comment]
@dperini Testing locally this does not appear to be fixed. My repro above has the same results as before.
