### ISSUE TITLE
querySelector > E

### ISSUE THREAD

**Issue by za-ek** [dperini/nwsapi#65]
Hi! This is my case:
```
...
<div id="my-id">
   <div>
      <a><span/></a>
      .... any number of a > span
      <span>
   </div>
   ... any number of the same structure
   <div>...</div>
</div>
...
```

I need separate values from a>span and div>span within function that holds ```('#my-id')```
I use function:
```
[...doc.querySelectorAll('#my-id > div')].map(row => {{
    rows: row.querySelectorAll('a > span') // ok, found all <a>
    root: row.querySelector(?)
}});
```
I have tried: ```> span```, ```span:root```, ```span:not(a > span)``` that are not valid and ```span:last-child```,```span:last-of-type``` that return span inside first <a> tag

How do I find the tag inside the row?

**Comment by dperini** [comment]
@za-ek 
there seems to be no issue here.
So I am closing this. Hope you found a way to do what you need.
If  that's not the case use a forum instead of filling an issue for a bug.
