### ISSUE TITLE
Missing support for :has() pseudo-class

### ISSUE THREAD

**Issue by KittyGiraudel** [dperini/nwsapi#72]
[Support for the `:has()` pseudo-class](https://caniuse.com/css-has) is getting _very_ good with only Firefox lacking support for wide adoption.

As far as I can tell from the [wiki](https://github.com/dperini/nwsapi/wiki/CSS-supported-selectors), it seems like nwsapi does not support `:has()` yet? In turns, this makes JSDOM throwing errors when using a selector containing the `:has()` pseudo-class — which is not ideal.

I _think_ the implementation should be relatively similar to the `:is()` and `:not()` pseudo-classes? Judging by the [spec](https://www.w3.org/TR/selectors-4/#relational), that is. What’s nice (I think?) about this pseudo-class is that it accepts a [`<forgiving-relative-selector-list>`](https://www.w3.org/TR/selectors-4/#typedef-forgiving-relative-selector-list) which means the validation of the argument doesn’t have to be strict.

**Comment by bramus** [comment]
Correction: `:has()` does not accept a [`<forgiving-relative-selector-list>`](https://www.w3.org/TR/selectors-4/#typedef-forgiving-relative-selector-list). It was initially specced that way but this no longer is the case as [per CSS WG Resolution](https://github.com/w3c/csswg-drafts/issues/7676#issuecomment-1341347244)

See the [last editors draft of the spec](https://drafts.csswg.org/selectors/#relational) for an updated definition.

**Comment by KittyGiraudel** [comment]
Ah, right. I forgot about this. Thank you Bramus. :)

**Comment by LyzioOh** [comment]
Hi, are PR welcome ?

**Comment by dperini** [comment]
@LyzioOh 
Yes they are much appreciated.
If related to bugs remember to include a small reproducible code showing how/when the bug happen.
In case of requests for new functionalities they will be discussed with jsdom maintainers.
For the remaining cases CSS Selector Level 4 is the target reference spec.
