### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by LucasLefevre** [dperini/nwsapi#76]
Hello @dperini 

Could you consider publishing a new release with the latest fixes?
A case sensitivity regression (that is now fixed, by looking at recent commits) prevents [o-spreadsheet](https://github.com/odoo/o-spreadsheet) to upgrade jest to more recent version

Thanks for you consideration :)
Lucas

**Comment by dperini** [comment]
@LucasLefevre 
yes a new release is planned next week.
There are new fixes and I would like to apply them before the new release takes place.

**Comment by dperini** [comment]
@LucasLefevre 
The latest 2.2.3 release has been published with the necessary fixes and improvements.
Hope it covers your needs.
