### ISSUE TITLE
Add documentation on supported selectors

### ISSUE THREAD

**Issue by Zirro** [dperini/nwsapi#8]
nwsapi needs an updated version of nwmatcher's [Supported Selectors](https://github.com/dperini/nwmatcher/wiki/CSS-supported-selectors) page, which includes all the new selectors it supports.

**Comment by dperini** [comment]
Sure ... I will start reviewing the documentation and add the missing parts.
At times, when in doubt, I need to ask for help, confirmation or review to somebody with enough knowledge on these matters. @domenic is doing great with answering questions however I know he is very busy on a long list of things, do you mind sharing your e-mail address so I have an additional reference ?

**Comment by Zirro** [comment]
Okay, that's alright. I've sent an email to the address on your profile.

**Comment by dperini** [comment]
Some documentation was revisited and corrected ... more to come.
Not a real issue, closing this.
