### ISSUE TITLE
fix: v2.2.3  was broken and v2.2.4 it was not published on npm

### ISSUE THREAD

**Issue by alexgwolff** [dperini/nwsapi#82]
Please release this revert: https://github.com/dperini/nwsapi/commit/23f9e2386ea9eeddd59cf851d02002cf7c84babb

**Comment by dperini** [comment]
@alexgwolff 
is that fixed with release 2.2.4 ?

**Comment by alexgwolff** [comment]
@dperini I have not tested

**Comment by bmuenzenmeyer** [comment]
i can view 2.2.4 now on the registry, so this can be closed?
