### ISSUE TITLE
:scope in the context of the Document (DOCUMENT_NODE) object does not refer to the root element

### ISSUE THREAD

**Issue by olegbarabanov** [dperini/nwsapi#93]
In the context of a [`Document`](https://developer.mozilla.org/en-US/docs/Web/API/Document) object (`DOCUMENT_NODE`), the `:scope` pseudo-class does not refer to the root element, according to the specification details [https://drafts.csswg.org/selectors-4/#the-scope-pseudo](https://drafts.csswg.org/selectors-4/#the-scope-pseudo).

## Minimal reproduction case:
```js
// browser (Chromium-based, Firefox, ...)
document.querySelector(':scope > head'); // => OK - return HTMLHeadElement element
document.querySelector(':scope > body'); // => OK - return HTMLBodyElement element

// nwsapi@2.2.7
NW.Dom.first(':scope > head'); // Error - return null
NW.Dom.first(':scope > body'); // Error - return null
```

Live example (in sandbox): [https://codepen.io/olegbarabanov/pen/qBQpzxR](https://codepen.io/olegbarabanov/pen/qBQpzxR)

## Note

**nwsapi version:** 2.2.7

**Comment by b-fuze** [comment]
You can pass the root node like this
```javascript
NW.Dom.first(':scope > head', document.documentElement);
```
in the case of no explicit context

**Comment by olegbarabanov** [comment]
> You can pass the root node like this
> 
> ```js
> NW.Dom.first(':scope > head', document.documentElement);
> ```
> 
> in the case of no explicit context. It probably doesn't solve the case of `NW.Dom.first(":scope", document)` incorrectly returning `null` when it should return the root element.

@b-fuze, thank you.

A similar solution using `document.documentElement` has already been proposed in a pending pull request (#94) to make the behavior of `:scope` on `document` the same as described in the [standard](https://drafts.csswg.org/selectors-4/#the-scope-pseudo) and how it works in browsers.

For now, explicitly passing `document.documentElement` is the best workaround when dealing with `:scope` and `document`.
