### ISSUE TITLE
:active always returning true since 2.2.7

### ISSUE THREAD

**Issue by SantoJambit** [dperini/nwsapi#99]
In https://github.com/jsdom/jsdom/issues/3610 I noticed, that the `:active selector` always returns true. This happened with nwsapi 2.2.7. You already have the fix/revert in the master branch, but not released yet. Any chance of this getting released soon?

Thanks

**Comment by antoniogamizbadger** [comment]
Looking forward to this! :D Thanks!!

**Comment by mxgit1090** [comment]
Looking forward to this for 1 month and more!! Thanks!!

**Comment by alopix** [comment]
Any change this is gonna be released soon? Have bee stuck updating `jsdom` since December due to this bug 😅

**Comment by dperini** [comment]
Forgive my absence but this was not under my control, health and other problems took the precedence over everything else in the last year. However I am ready to start again and try recover your trust by fixing most existing problems.
I surely need everybody help testing and for this reason I opted to use WPT to have a reliable tool and environment to test. Stay  tuned !

**Comment by alopix** [comment]
Sorry to hear you were unwell @dperini and glad to hear you are better! Health ansd wellbeing definitely come first!

**Comment by SantoJambit** [comment]
I've just installed 2.2.9 and it seems to work. Thanks :)

**Comment by WesCossick** [comment]
@dperini This issue has regressed in v2.2.10. It was fixed in v2.2.8 and v2.2.9, but has reappeared in v2.2.10.
